source 'https://rubygems.org'

gem 'coffee-rails', '~> 4.0.0'
gem 'rails', '4.1.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'therubyracer',  platforms: :ruby
gem 'devise', '3.2.2'
gem 'bootsy'
gem 'bootstrap-datepicker-rails'
gem 'paperclip'
gem 'fog'
gem 'magnific-popup-rails'
gem 'gritter', '1.1.0'
gem 'jquery-rails'
gem 'the_comments', '~> 2.2.1'
gem 'haml'
gem 'turbolinks'
gem 'acts_as_commentable_with_threading'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'mini_magick', '~> 3.7.0'
gem 'awesome_nested_set', '~> 3.0.0.rc.3'
gem 'bcrypt', '~> 3.1.7'
gem 'bootstrap-sass', '~> 3.1.1'
gem 'tzinfo-data', platforms: [:mingw, :mswin]
gem 'bootstrap-modal-rails'
gem 'net-ssh'
gem 'capistrano'
